# Generated by Django 5.1.8 on 2025-04-26 17:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_type', models.TextField(blank=True, null=True)),
                ('value', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ElectricityBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('electricity_bill', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('electricity_bill_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Inquirybroker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=255, null=True)),
                ('name', models.CharField(max_length=255)),
                ('contact', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('invoice_name', models.CharField(max_length=255)),
                ('invoice_no', models.CharField(max_length=50, unique=True)),
                ('in_gst', models.CharField(max_length=15)),
                ('in_pan', models.CharField(max_length=10)),
                ('in_hsn_code', models.CharField(max_length=15)),
                ('to_gst', models.CharField(max_length=15)),
                ('to_pan', models.CharField(max_length=10)),
                ('to_hsn_code', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('description', models.TextField()),
                ('gross_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('state_code', models.CharField(max_length=5)),
                ('sgst', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('cgst', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('igst', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_status', models.CharField(choices=[('Paid', 'Paid'), ('Pending', 'Pending'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OfficeRent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('rent_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('contact', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='VehicleInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('contact', models.CharField(max_length=255, null=True)),
                ('Vehicle_name', models.CharField(max_length=255, null=True)),
                ('budget', models.CharField(max_length=255, null=True)),
                ('model', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WifiBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('bill_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StaffSalary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salaries', to='dealership.staff')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('inventory_status', models.CharField(blank=True, choices=[('IN', 'In Inventory'), ('OUT', 'Out of Inventory')], default='IN', max_length=3, null=True)),
                ('vehicle_type', models.CharField(choices=[('car', 'Car'), ('bus', 'Bus'), ('truck', 'Truck'), ('three_wheelers', 'Three Wheelers')], default='car', max_length=20)),
                ('vehicle_id', models.AutoField(primary_key=True, serialize=False)),
                ('vehicle_make', models.CharField(max_length=50)),
                ('vehicle_model', models.CharField(max_length=50)),
                ('year_of_manufacturing', models.IntegerField()),
                ('year_of_registration', models.IntegerField(blank=True, null=True)),
                ('chassis_number', models.CharField(max_length=5, verbose_name='Vehicle Identification Number (VIN)')),
                ('engine_number', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('osn_number', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('license_plate_number', models.CharField(max_length=15, unique=True)),
                ('odometer_reading_kms', models.PositiveIntegerField()),
                ('color', models.CharField(max_length=30)),
                ('fuel_type', models.CharField(max_length=30)),
                ('transmission_type', models.CharField(max_length=30)),
                ('seller_name_company_name', models.CharField(max_length=100)),
                ('mobile_number', models.CharField(max_length=15)),
                ('email_address', models.EmailField(blank=True, max_length=254, null=True)),
                ('proof_of_ownership_document', models.FileField(blank=True, null=True, upload_to='ownership_documents/')),
                ('inspection_date', models.DateField(blank=True, null=True)),
                ('condition_grade', models.CharField(blank=True, choices=[('Excellent', 'Excellent'), ('Good', 'Good'), ('Fair', 'Fair'), ('Poor', 'Poor')], max_length=20, null=True)),
                ('tires_condition', models.CharField(blank=True, choices=[('0-25', '0-25%'), ('25-50', '25-50%'), ('50-75', '50-75%'), ('75-100', '75-100%')], default='50-75', max_length=10, null=True)),
                ('damage_details_if_any', models.CharField(blank=True, max_length=100, null=True)),
                ('engine_condition', models.CharField(blank=True, max_length=100, null=True)),
                ('interior_condition', models.CharField(blank=True, choices=[('Excellent', 'Excellent'), ('Good', 'Good'), ('Fair', 'Fair'), ('Poor', 'Poor')], default='Good', max_length=20, null=True)),
                ('upload_image_of_vehicle', models.ImageField(blank=True, null=True, upload_to='vehicle_images/')),
                ('proof_of_ownership', models.FileField(blank=True, null=True, upload_to='ownership_documents/')),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('date_of_purchase', models.DateField(blank=True, null=True)),
                ('payment_method', models.CharField(blank=True, max_length=30, null=True)),
                ('purchase_agreement', models.FileField(blank=True, null=True, upload_to='purchase_agreements/')),
                ('arrival_date', models.DateField(blank=True, null=True)),
                ('storage_location', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('estimated_selling_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('purchase', 'Purchase Payment'), ('selling', 'Selling Payment')], default='purchase', max_length=10, null=True)),
                ('slot_number', models.CharField(choices=[('Slot 1', 'Slot 1'), ('Slot 2', 'Slot 2'), ('Slot 3', 'Slot 3'), ('Slot 4', 'Slot 4'), ('Slot 5', 'Slot 5'), ('Slot 6', 'Slot 6'), ('Slot 7', 'Slot 7'), ('Slot 8', 'Slot 8'), ('Slot 9', 'Slot 9'), ('Slot 10', 'Slot 10')], max_length=10)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_of_payment', models.DateField()),
                ('payment_mode', models.CharField(blank=True, choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('cheque', 'Cheque'), ('upi', 'UPI'), ('credit_card', 'Credit Card'), ('debit_card', 'Debit Card')], max_length=20, null=True)),
                ('payment_remark', models.TextField(blank=True, null=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='dealership.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='OutboundVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_current_images', models.ImageField(blank=True, null=True, upload_to='outbound_vehicle_images/')),
                ('vehicle_current_condition', models.CharField(choices=[('Excellent', 'Excellent'), ('Good', 'Good'), ('Bad', 'Bad'), ('Worse', 'Worse')], default='Good', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('buyers_name', models.CharField(max_length=100)),
                ('buyers_contact_details', models.CharField(max_length=15)),
                ('buyers_address', models.TextField(blank=True, null=True)),
                ('buyers_proof_of_identity', models.FileField(blank=True, null=True, upload_to='buyer_proofs/')),
                ('delivery_status', models.CharField(default='Pending', max_length=50)),
                ('outbound_date', models.DateField()),
                ('estimated_delivery_date', models.DateField(blank=True, null=True)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('other_expense', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dealership.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_type', models.CharField(max_length=100)),
                ('maintenance_date', models.DateField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('person_in_charge', models.CharField(blank=True, max_length=100, null=True)),
                ('receipt', models.FileField(blank=True, null=True, upload_to='maintenance_receipts/')),
                ('payment_mode', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('vehicle', models.ForeignKey(db_column='vehicle_id', on_delete=django.db.models.deletion.CASCADE, to='dealership.vehicle')),
            ],
        ),
    ]
