# Generated by Django 5.1.8 on 2025-05-31 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealership', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='chassis_number',
            field=models.CharField(max_length=17, verbose_name='Vehicle Identification Number (VIN)'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='upload_image_of_vehicle',
            field=models.TextField(blank=True, null=True),
        ),
    ]
